namespace LaundryMgmt.Mobile;

public static class Program
{
    // Provide a simple entry point so the project compiles on all target frameworks.
    // The real MAUI entry is normally generated by the SDK when UseMaui is true,
    // but adding this prevents CS5001 during certain build scenarios.
    public static void Main(string[] args) { }
}
